#!/usr/bin/env bash

PATCH_FILE="working-tree.patch" 
NPM_BIN="./node_modules/.bin"

function cleanup {
    exit_code=$?
    if [ -f "$PATCH_FILE" ]; then
        patch -p0 < "$PATCH_FILE"
        rm "$PATCH_FILE"
    fi
    exit $exit_code
}

#Прибираемся при выходе из скрипта
trap cleanup EXIT SIGINT SIGHUP

# Создаем  патч
git diff > "$PATCH_FILE" --no-prefix
# Сбрасываем не застэйдженный изменения
git checkout -- .

# получаем список файлов в которых были изменения, которые мы хотим закоммитить
git_cached_styles_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.css' '*.scss' '*.sass' '*.less' | xargs)
git_cached_js_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.js' | xargs)

if [ "$git_cached_styles_files" ]; then
    #Собственно натравливаем CSScomb.js
    echo "--------CSScomb-------"
    $NPM_BIN/csscomb -v -l $git_cached_styles_files
    echo "--------CSScomb-------"
fi

if [ "$git_cached_js_files" ]; then
    #Собственно натравливаем jshint.js
    echo "--------JShint--------"
    $NPM_BIN/jshint $git_cached_js_files
    echo "--------JShint--------"
fi
